In [1]:
#import dependencies and setup
import matplotlib.pyplot as plt
import pandas as pd
import scipy.stats as st

In [2]:
#load files
food_supply_to_load = "../COVID_Diet_Data/Food_Supply_Quantity_kg_Data.csv"

#read file and store as dataframe
food_supply = pd.read_csv(food_supply_to_load)
pd
food_supply

,Country,Alcoholic Beverages,Animal fats,Animal Products,"Aquatic Products, Other",Cereals - Excluding Beer,Eggs,"Fish, Seafood",Fruits - Excluding Wine,Meat,...,Vegetables,Vegetal Products,Obesity,Undernourished,Confirmed,Deaths,Recovered,Active,Population,Unit (all except Population)
0,Afghanistan,0.0014,0.1973,9.4341,0.0000,24.8097,0.2099,0.0350,5.3495,1.2020,...,6.7642,40.5645,4.5,29.8,0.142134,0.006186,0.123374,0.012574,38928000.0,%
1,Albania,1.6719,0.1357,18.7684,0.0000,5.7817,0.5815,0.2126,6.7861,1.8845,...,11.7753,31.2304,22.3,6.2,2.967301,0.050951,1.792636,1.123714,2838000.0,%
2,Algeria,0.2711,0.0282,9.6334,0.0000,13.6816,0.5277,0.2416,6.3801,1.1305,...,11.6484,40.3651,26.6,3.9,0.244897,0.006558,0.167572,0.070767,44357000.0,%
3,Angola,5.8087,0.0560,4.9278,0.0000,9.1085,0.0587,1.7707,6.0005,2.0571,...,2.3041,45.0722,6.8,25,0.061687,0.001461,0.056808,0.003419,32522000.0,%
4,Antigua and Barbuda,3.5764,0.0087,16.6613,0.0000,5.9960,0.2274,4.1489,10.7451,5.6888,...,5.4495,33.3233,19.1,NaN,0.293878,0.007143,0.190816,0.095918,98000.0,%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
165,Venezuela (Bolivarian Republic of),2.5952,0.0403,14.7565,0.0000,12.9253,0.3389,0.9456,7.6460,3.8328,...,4.1474,35.2416,25.2,21.2,0.452585,0.004287,0.424399,0.023899,28645000.0,%
166,Vietnam,1.4591,0.1640,8.5765,0.0042,16.8740,0.3077,2.6392,5.9029,4.4382,...,11.9508,41.4232,2.1,9.3,0.002063,0.000036,0.001526,0.000501,96209000.0,%
167,Yemen,0.0364,0.0446,5.7874,0.0000,27.2077,0.2579,0.5240,5.1344,2.7871,...,3.2135,44.2126,14.1,38.9,0.007131,0.002062,0.004788,0.000282,29826000.0,%
168,Zambia,5.7360,0.0829,6.0197,0.0000,21.1938,0.3399,1.6924,1.0183,1.8427,...,3.4649,43.9789,6.5,46.7,0.334133,0.004564,0.290524,0.039045,18384000.0,%
169,Zimbabwe,4.0552,0.0755,8.1489,0.0000,22.6240,0.2678,0.5518,2.2000,2.6142,...,2.3213,41.8526,12.3,51.3,0.232033,0.008854,0.190964,0.032214,14863000.0,%

In [3]:
country_count = len(food_supply["Country"].unique())
country_count

170

In [4]:
food_supply.head()

,Country,Alcoholic Beverages,Animal fats,Animal Products,"Aquatic Products, Other",Cereals - Excluding Beer,Eggs,"Fish, Seafood",Fruits - Excluding Wine,Meat,...,Vegetables,Vegetal Products,Obesity,Undernourished,Confirmed,Deaths,Recovered,Active,Population,Unit (all except Population)
0,Afghanistan,0.0014,0.1973,9.4341,0.0,24.8097,0.2099,0.0350,5.3495,1.2020,...,6.7642,40.5645,4.5,29.8,0.142134,0.006186,0.123374,0.012574,38928000.0,%
1,Albania,1.6719,0.1357,18.7684,0.0,5.7817,0.5815,0.2126,6.7861,1.8845,...,11.7753,31.2304,22.3,6.2,2.967301,0.050951,1.792636,1.123714,2838000.0,%
2,Algeria,0.2711,0.0282,9.6334,0.0,13.6816,0.5277,0.2416,6.3801,1.1305,...,11.6484,40.3651,26.6,3.9,0.244897,0.006558,0.167572,0.070767,44357000.0,%
3,Angola,5.8087,0.0560,4.9278,0.0,9.1085,0.0587,1.7707,6.0005,2.0571,...,2.3041,45.0722,6.8,25,0.061687,0.001461,0.056808,0.003419,32522000.0,%
4,Antigua and Barbuda,3.5764,0.0087,16.6613,0.0,5.9960,0.2274,4.1489,10.7451,5.6888,...,5.4495,33.3233,19.1,NaN,0.293878,0.007143,0.190816,0.095918,98000.0,%

In [11]:
#Top 10 countries with the most deaths
most_deaths = food_supply.sort_values("Deaths", ascending=False)
most_deaths

,Country,Alcoholic Beverages,Animal fats,Animal Products,"Aquatic Products, Other",Cereals - Excluding Beer,Eggs,"Fish, Seafood",Fruits - Excluding Wine,Meat,...,Vegetables,Vegetal Products,Obesity,Undernourished,Confirmed,Deaths,Recovered,Active,Population,Unit (all except Population)
14,Belgium,5.3730,0.8559,17.7279,0.0010,6.6704,0.6487,1.1325,4.1623,3.2370,...,6.8161,32.2637,24.5,<2.5,6.286322,0.185428,0.000000,6.100894,11515000.0,%
138,Slovenia,4.9933,1.1248,18.9196,0.0005,7.6345,0.5376,0.6515,6.4367,4.1610,...,5.0020,31.0774,22.5,<2.5,8.235901,0.171755,7.312934,0.751213,2103000.0,%
159,United Kingdom,5.2632,0.2754,18.8798,0.0006,6.5412,0.6210,1.0911,4.9551,4.4181,...,4.5851,31.1116,29.5,<2.5,5.868483,0.167220,0.015161,5.686102,67160000.0,%
38,Czechia,9.8498,0.8945,17.8065,0.0006,5.6937,0.4964,0.5355,3.3962,4.7618,...,4.5289,32.1944,28.5,<2.5,9.612841,0.159845,8.555328,0.897667,10716000.0,%
74,Italy,3.1892,0.2834,19.0329,0.0005,8.5417,0.6247,1.5816,6.0207,4.2963,...,6.9463,30.9671,22.9,<2.5,4.353685,0.150927,3.494529,0.708229,60296000.0,%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80,Kiribati,0.2970,0.0486,8.8958,0.0000,8.2747,0.1640,6.1065,5.8907,2.3856,...,4.1389,41.1042,45.6,2.7,NaN,NaN,NaN,NaN,125000.0,%
81,"Korea, North",0.8981,0.0010,3.3933,0.0010,17.9378,0.4668,1.1568,6.1383,1.3872,...,12.8082,46.6046,7.1,47.8,NaN,NaN,NaN,NaN,25779000.0,%
105,Myanmar,0.2195,0.1751,13.5188,0.0034,16.7608,0.4613,4.0424,4.0287,4.9753,...,7.0725,36.4807,5.7,10.6,NaN,NaN,NaN,NaN,54704000.0,%
109,New Caledonia,5.0363,0.0821,11.7818,0.0804,8.5840,0.7494,2.0361,5.5855,5.8687,...,5.5941,38.2208,NaN,7.1,NaN,NaN,NaN,NaN,295000.0,%
155,Turkmenistan,0.5038,0.3373,16.0611,0.0000,14.8029,0.5139,0.2137,4.1441,4.3767,...,10.4014,33.9389,17.5,5.4,NaN,NaN,NaN,NaN,6031000.0,%

In [12]:
top_ten_deaths = most_deaths.head(10)
top_ten_deaths

,Country,Alcoholic Beverages,Animal fats,Animal Products,"Aquatic Products, Other",Cereals - Excluding Beer,Eggs,"Fish, Seafood",Fruits - Excluding Wine,Meat,...,Vegetables,Vegetal Products,Obesity,Undernourished,Confirmed,Deaths,Recovered,Active,Population,Unit (all except Population)
14,Belgium,5.3730,0.8559,17.7279,0.0010,6.6704,0.6487,1.1325,4.1623,3.2370,...,6.8161,32.2637,24.5,<2.5,6.286322,0.185428,0.000000,6.100894,11515000.0,%
138,Slovenia,4.9933,1.1248,18.9196,0.0005,7.6345,0.5376,0.6515,6.4367,4.1610,...,5.0020,31.0774,22.5,<2.5,8.235901,0.171755,7.312934,0.751213,2103000.0,%
159,United Kingdom,5.2632,0.2754,18.8798,0.0006,6.5412,0.6210,1.0911,4.9551,4.4181,...,4.5851,31.1116,29.5,<2.5,5.868483,0.167220,0.015161,5.686102,67160000.0,%
38,Czechia,9.8498,0.8945,17.8065,0.0006,5.6937,0.4964,0.5355,3.3962,4.7618,...,4.5289,32.1944,28.5,<2.5,9.612841,0.159845,8.555328,0.897667,10716000.0,%
74,Italy,3.1892,0.2834,19.0329,0.0005,8.5417,0.6247,1.5816,6.0207,4.2963,...,6.9463,30.9671,22.9,<2.5,4.353685,0.150927,3.494529,0.708229,60296000.0,%
18,Bosnia and Herzegovina,4.7876,0.0585,12.4319,0.0000,8.7152,0.2576,0.2465,4.6409,1.8165,...,11.6394,37.5645,19.4,<2.5,3.762085,0.145535,2.960317,0.656233,3281000.0,%
114,North Macedonia,1.9045,0.3784,12.0639,0.0000,7.3937,0.2847,0.3507,5.0893,2.0683,...,14.5512,37.9330,23.9,3.2,4.548029,0.140192,4.025721,0.382115,2080000.0,%
161,United States of America,4.8647,0.1681,21.2352,0.0020,5.5048,0.7860,1.1287,4.5432,6.2645,...,5.7249,28.7587,37.3,<2.5,8.159922,0.140103,0.000000,8.019819,329878000.0,%
123,Portugal,4.7147,0.4077,18.6614,0.0005,6.2984,0.4053,2.7295,6.5126,4.5168,...,7.3366,31.3374,23.2,<2.5,7.429605,0.136070,5.846836,1.446699,10255000.0,%
21,Bulgaria,7.0834,0.2488,17.2483,0.0103,8.8750,0.5924,0.4845,3.9812,4.0073,...,6.2037,32.7435,27.4,3.6,3.227256,0.134416,2.788956,0.303883,6927000.0,%

In [13]:
least_deaths = food_supply.sort_values("Deaths", ascending=True)
least_deaths

,Country,Alcoholic Beverages,Animal fats,Animal Products,"Aquatic Products, Other",Cereals - Excluding Beer,Eggs,"Fish, Seafood",Fruits - Excluding Wine,Meat,...,Vegetables,Vegetal Products,Obesity,Undernourished,Confirmed,Deaths,Recovered,Active,Population,Unit (all except Population)
85,Lao People's Democratic Republic,0.7883,0.0979,3.6579,0.0006,16.3943,0.1063,1.4213,8.8158,1.7111,...,11.6410,46.3416,4.5,16.5,0.000621,0.0,0.000566,0.000055,7242000.0,%
139,Solomon Islands,0.8298,0.1038,3.8504,0.0121,9.0233,0.0826,2.2840,3.2798,0.8897,...,1.1223,46.1492,20.5,8.9,0.002378,0.0,0.001399,0.000979,715000.0,%
150,Timor-Leste,0.4459,0.0897,5.4983,0.0000,26.3320,0.1025,1.0225,2.1027,4.0376,...,3.1867,44.5030,2.9,24.9,0.006070,0.0,0.004628,0.001442,1318000.0,%
24,Cambodia,4.5783,0.0377,6.0800,0.0000,24.8906,0.1310,4.2369,2.3184,1.2247,...,3.0072,43.9195,3.5,16.4,0.003059,0.0,0.002930,0.000129,15497000.0,%
128,Saint Kitts and Nevis,4.0867,0.1735,14.0252,0.0000,6.3135,0.3868,3.4174,7.5449,7.8207,...,4.2090,35.9677,23.1,NaN,0.074074,0.0,0.066667,0.007407,54000.0,%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80,Kiribati,0.2970,0.0486,8.8958,0.0000,8.2747,0.1640,6.1065,5.8907,2.3856,...,4.1389,41.1042,45.6,2.7,NaN,NaN,NaN,NaN,125000.0,%
81,"Korea, North",0.8981,0.0010,3.3933,0.0010,17.9378,0.4668,1.1568,6.1383,1.3872,...,12.8082,46.6046,7.1,47.8,NaN,NaN,NaN,NaN,25779000.0,%
105,Myanmar,0.2195,0.1751,13.5188,0.0034,16.7608,0.4613,4.0424,4.0287,4.9753,...,7.0725,36.4807,5.7,10.6,NaN,NaN,NaN,NaN,54704000.0,%
109,New Caledonia,5.0363,0.0821,11.7818,0.0804,8.5840,0.7494,2.0361,5.5855,5.8687,...,5.5941,38.2208,NaN,7.1,NaN,NaN,NaN,NaN,295000.0,%
155,Turkmenistan,0.5038,0.3373,16.0611,0.0000,14.8029,0.5139,0.2137,4.1441,4.3767,...,10.4014,33.9389,17.5,5.4,NaN,NaN,NaN,NaN,6031000.0,%

In [14]:
bottom_10_deaths = least_deaths.head(10)
bottom_10_deaths

,Country,Alcoholic Beverages,Animal fats,Animal Products,"Aquatic Products, Other",Cereals - Excluding Beer,Eggs,"Fish, Seafood",Fruits - Excluding Wine,Meat,...,Vegetables,Vegetal Products,Obesity,Undernourished,Confirmed,Deaths,Recovered,Active,Population,Unit (all except Population)
85,Lao People's Democratic Republic,0.7883,0.0979,3.6579,0.0006,16.3943,0.1063,1.4213,8.8158,1.7111,...,11.6410,46.3416,4.5,16.5,0.000621,0.000000,0.000566,0.000055,7242000.0,%
139,Solomon Islands,0.8298,0.1038,3.8504,0.0121,9.0233,0.0826,2.2840,3.2798,0.8897,...,1.1223,46.1492,20.5,8.9,0.002378,0.000000,0.001399,0.000979,715000.0,%
150,Timor-Leste,0.4459,0.0897,5.4983,0.0000,26.3320,0.1025,1.0225,2.1027,4.0376,...,3.1867,44.5030,2.9,24.9,0.006070,0.000000,0.004628,0.001442,1318000.0,%
24,Cambodia,4.5783,0.0377,6.0800,0.0000,24.8906,0.1310,4.2369,2.3184,1.2247,...,3.0072,43.9195,3.5,16.4,0.003059,0.000000,0.002930,0.000129,15497000.0,%
128,Saint Kitts and Nevis,4.0867,0.1735,14.0252,0.0000,6.3135,0.3868,3.4174,7.5449,7.8207,...,4.2090,35.9677,23.1,NaN,0.074074,0.000000,0.066667,0.007407,54000.0,%
164,Vanuatu,0.2424,0.0793,6.6244,0.0000,6.4102,0.1875,2.1649,5.8103,2.7466,...,3.9175,43.3737,23.5,7.2,0.000312,0.000000,0.000312,0.000000,321000.0,%
131,Samoa,1.4236,0.2262,11.1630,0.1236,3.6768,0.1314,2.7788,10.7845,5.7993,...,1.1656,38.8349,45.5,2.7,0.001000,0.000000,0.001000,0.000000,200000.0,%
41,Dominica,0.9410,0.0319,8.9011,0.0000,3.4014,0.1244,1.4188,19.3028,2.7820,...,4.6371,41.0989,28.2,6.2,0.168056,0.000000,0.152778,0.015278,72000.0,%
160,United Republic of Tanzania,4.5185,0.0403,4.8022,0.0000,10.4453,0.0300,0.5828,6.8147,0.7902,...,3.9520,45.1973,7.1,30.7,0.000852,0.000035,0.000306,0.000511,59734000.0,%
166,Vietnam,1.4591,0.1640,8.5765,0.0042,16.8740,0.3077,2.6392,5.9029,4.4382,...,11.9508,41.4232,2.1,9.3,0.002063,0.000036,0.001526,0.000501,96209000.0,%